services:
  - type: web
    name: hr-integration-server
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node realtime-server.js
    healthCheckPath: /api/test
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false